import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { auth } from "../../auth";
import { getI18n } from "@/i18n/server";
import { I18nProvider } from "@/i18n/I18nProvider";
import Sidebar from "@/components/layout/Sidebar";
import BottomNav from "@/components/layout/BottomNav";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const t = await getI18n();

  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900">
        <I18nProvider dictionary={t}>
          {session ? (
            <div className="flex h-screen overflow-hidden">
              <Sidebar session={session} />
              <main className="flex-1 md:ml-64 w-full h-full overflow-y-auto pb-16 md:pb-0">
                {children}
              </main>
              <BottomNav session={session} />
            </div>
          ) : (
            <main className="flex-1 w-full h-full">
              {children}
            </main>
          )}
        </I18nProvider>
      </body>
    </html>
  );
}
