import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { auth } from "../../auth";
import Sidebar from "@/components/layout/Sidebar";
import BottomNav from "@/components/layout/BottomNav";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900">
        {/* 네비게이션이 들어간 반응형 레이아웃 뼈대 */}
        {session ? (
          <div className="flex h-screen overflow-hidden">
            <Sidebar session={session} />
            <main className="flex-1 md:ml-64 w-full h-full overflow-y-auto pb-16 md:pb-0">
              {children}
            </main>
            <BottomNav session={session} />
          </div>
        ) : (
          <main className="flex-1 w-full h-full">
            {children}
          </main>
        )}
      </body>
    </html>
  );
}
